=== mwelss-fhg/license-manager/license-manager-client-library/src/main/resources/license-profile.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "keyword",
    "licenseName",
    "copyright",
    "rtuRequired"
  ],
  "properties": {
    "keyword": {
      "type": "string"
    },
    "licenseName": {
      "type": "string"
    },
    "intro": {
      "type": "string"
    },
    "copyright": {
      "type": "object",
      "required": [
        "year",
        "company",
        "suffix"
      ],
      "properties": {
        "year": {
          "type": "integer",
          "default": 2019
        },
        "company": {
          "type": "string"
        },
        "suffix": {
          "type": "string"
        }
      }
    },
    "softwareType": {
      "type": "string"
    },
    "companyName": {
      "type": "string"
    },
    "contact": {
      "type": "object",
      "required": [
        "name",
        "URL",
        "email"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "URL": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      }
    },
    "additionalInfo": {
      "type": "string"
    },
    "rtuRequired":{
      "type": "boolean",
      "description": "When true a right to use must be provided by the supplier to enable use."
    }
  }
}

=== mwelss-fhg/license-manager/license-profile-editor/src/assets/examples/apache-2.0-company-a.json
{
  "keyword": "Apache-2.0",
  "licenseName": "Apache License 2.0",
  "copyright": {
    "year": 2019,
    "company": "Company A",
    "suffix": "All Rights Reserved"
  },
  "softwareType": "Machine Learning Model",
  "companyName": "Company A",
  "contact": {
    "name": "Company A  Team Member",
    "URL": "http://companya.com",
    "email": "support@companya.com"
  },
  "rtuRequired": true
}
